#!/bin/bash
read -p "Cual es el nombre del usuario que se restablece: " namer
 if cat /etc/passwd |grep $namer: > /dev/null
 then
 echo " "
 else
 clear
 echo "Usuario $namer no existe"
 exit
 fi
clear
echo -e "\033[1;33mO que vc desea redefinir ?\033[1;30m
1) Numero de logins
2) Fecha de Expiracion
3) Cambiar contraseña de usuario"
read -p "opcion: " option
if [ $option -eq 1 ]; then
read -p "Cuál es el nuevo límite de inicio de sesión: " liml
limite $namer $liml
exit 0
fi

if [ $option -eq 2 ]; then
echo "Cuál es la nueva fecha : formato AAAA/MM/DD"
read -p ": " date
chage -E $date $namer 2> /dev/null
echo -e "\033[1;31mUsuario $namer Date: $date\033[0m"
exit
fi
if [ $option -eq 3 ]
then
read -p "Cuál es la nueva contraseña para $namer: " senha
(echo "$senha" ; echo "$senha" ) |passwd $namer > /dev/null 2>/dev/null
echo "$senha" > /etc/VpsPackdir/senha/$namer
echo "Nueva contraseña aplicada"
exit
fi
